development:
  adapter: mysql2
  database: hackday_development
  host: localhost
  username: root
  password: 
  encoding: utf8

test:
  adapter: mysql2
  database: hackday_test
  host: localhost
  username: root
  password: 
  encoding: utf8

#production:
#  adapter: mysql2
#  database: gdh_production
#  host: zooniverse-db4.cezuuccr9cw6.us-east-1.rds.amazonaws.com
#  username: zooteach
#  password: Zbnsp_#1
#  encoding: utf8

