development:
  adapter: mysql2
  database: hackday_development
  host: localhost
  username: root
  password: 
  encoding: utf8

test:
  adapter: mysql2
  database: hackday_test
  host: localhost
  username: root
  password: 
  encoding: utf8



